
ARG GO_VERSION=1.20
FROM golang:${GO_VERSION} AS build

COPY . /github.com/bear1278/GoTestBot/
WORKDIR /github.com/bear1278/GoTestBot/

RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=bind,source=go.sum,target=go.sum \
    --mount=type=bind,source=go.mod,target=go.mod \
    go mod download -x


RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 go build -o /bin/server cmd/bot/main.go


FROM alpine:latest AS final

# Install any runtime dependencies that are needed to run your application.
# Leverage a cache mount to /var/cache/apk/ to speed up subsequent builds.
RUN --mount=type=cache,target=/var/cache/apk \
    apk --update add \
        ca-certificates \
        tzdata \
        && \
        update-ca-certificates

# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
USER appuser
WORKDIR /app/
# Copy the executable from the "build" stage.
COPY --from=build /bin/server .
COPY --from=build /github.com/bear1278/GoTestBot/configs/ configs/
# Expose the port that the application listens on.
EXPOSE 1278

# What the container should run when it is started.
ENTRYPOINT [ "/app/server" ]
